typography_spectrum: 0.63457
color:
  brandColors:
    - '#ffffff'
    - '#ffbc42'
    - '#d81159'
    - '#218380'
    - '#ea614d'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
name: Matt Deloughry
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: ttaM
purpose: []
